version: '3'
services:
  web:
    image: nginx
    ports:
    - 80:80
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
  app:
    build: .
    volumes:
      - .:/task-manager-api
    environment:
      - RAILS_ENV=${RAILS_ENV}
    ports:
      - "5000:3000"
    depends_on:
      - db
