version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 5000 -b '0.0.0.0'
    volumes:
      - .:/task-manager-api
    ports:
      - "5000:5000"
    depends_on:
      - db
