default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: task-manager-api_development

test:
  <<: *default
  database: task-manager-api_test

production:
  <<: *default
  database: task-manager-api
